spring:
  application:
    name: notification
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_ENDPOINT_URL}:3306/${DATABASE_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

  data:
    mongodb:
      uri: ${MONGO_DB_URI}
      port: 27017

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  flyway:
    baseline-on-migrate: true
    baseline-description: 0
    enabled: true

  rabbitmq:
    host: ${RABBIT_MQ_HOST}
    port: ${RABBIT_MQ_PORT}
    username: ${RABBIT_MQ_USERNAME}
    password: ${RABBIT_MQ_PASSWORD}
    ssl:
      enabled: true

  config:
    import: optional:application-secret.properties
    activate:
      on-profile: local

rabbitmq:
  queue:
    name: notification
  exchange:
    name: notification-exchange
  routing:
    key: key

server:
  port: 8081